In [5]:
import pandas as pd

df = pd.read_csv(r'..\data\raw\personal_transactions.csv')
df.head()

,Date,Description,Amount,Transaction Type,Category,Account Name
0,01/01/2018,Amazon,11.11,debit,Shopping,Platinum Card
1,01/02/2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking
2,01/02/2018,Thai Restaurant,24.22,debit,Restaurants,Silver Card
3,01/03/2018,Credit Card Payment,2298.09,credit,Credit Card Payment,Platinum Card
4,01/04/2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806 entries, 0 to 805
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              806 non-null    object
 1   Description       806 non-null    object
 2   Amount            806 non-null    float64
 3   Transaction Type  806 non-null    object
 4   Category          806 non-null    object
 5   Account Name      806 non-null    object
dtypes: float64(1), object(5)
memory usage: 37.9+ KB

In [12]:
df.isnull().sum()

Date                0
Description         0
Amount              0
Transaction Type    0
Category            0
Account Name        0
dtype: int64

In [8]:
df.describe()

            Amount
count   806.000000
mean    273.391489
std     667.630374
min       1.750000
25%      15.687500
50%      37.480000
75%     117.680000
max    9200.000000

In [11]:
df.shape

(806, 6)

In [15]:
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')